# Generated by Django 2.2 on 2021-02-19 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(verbose_name='duration of file in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='name of the title')),
                ('author', models.CharField(max_length=100, verbose_name='author name')),
                ('narrator', models.CharField(max_length=100, verbose_name='narrator name')),
            ],
            options={
                'verbose_name': 'audiobook',
                'verbose_name_plural': 'audiobooks',
            },
        ),
        migrations.CreateModel(
            name='PodCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(verbose_name='duration of file in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='name of the podcast')),
                ('host', models.CharField(max_length=100, verbose_name='host_name')),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name="participant's name"), blank=True, null=True, size=10)),
            ],
            options={
                'verbose_name': 'podcast',
                'verbose_name_plural': 'podcasts',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(verbose_name='duration of file in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='name of the song')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
            },
        ),
    ]
